name: Publish NuGet
 
on:
 push:
  branches: 
   - master
  paths: 
   - ClassLibraryTest/ClassLibraryTest.csproj
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore ClassLibraryTest.sln
 
    - name: Build and Publish Library
      run: msbuild ClassLibraryTest.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
      
    - name: Pack Up
      run: dotnet pack ClassLibraryTest --configuration Release
      
    - name: Add private GitHub registry to NuGet
      run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/tgoze/index.json -Username tjgoze@gmail.com -Password ${{ secrets.GITHUB_TOKEN }}

    - name: Push generated package to GitHub registry
      run: nuget push ClassLibraryTest\bin\Release\*.nupkg -Source "GPR" -SkipDuplicate
