name: Publish NuGet
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore ClassLibraryTest.sln
 
    - name: Build and Publish Web App
      run: msbuild ClassLibraryTest.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_lib
        path: ClassLibraryTest\bin\Release\netstandard2.0

    - name: Publish Nuget to Packages
      run: nuget push ClassLibraryTest\bin\Release\netstandard2.0\publish\*.nupkg a8e444e99b791cbada91bf73e90477805e0b5a8d -Source https://nuget.pkg.github.com/tgoze/index.json 
